/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpskillRouteImport } from './routes/upskill'
import { Route as SprintRouteImport } from './routes/sprint'
import { Route as SpeakWithAiRouteImport } from './routes/speak-with-ai'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RUsernameRouteImport } from './routes/r.$username'
import { Route as NdaExchangeIdRouteImport } from './routes/nda.$exchangeId'
import { Route as CheckoutGigIdRouteImport } from './routes/checkout.$gigId'

const UpskillRoute = UpskillRouteImport.update({
  id: '/upskill',
  path: '/upskill',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintRoute = SprintRouteImport.update({
  id: '/sprint',
  path: '/sprint',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakWithAiRoute = SpeakWithAiRouteImport.update({
  id: '/speak-with-ai',
  path: '/speak-with-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RUsernameRoute = RUsernameRouteImport.update({
  id: '/r/$username',
  path: '/r/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const NdaExchangeIdRoute = NdaExchangeIdRouteImport.update({
  id: '/nda/$exchangeId',
  path: '/nda/$exchangeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutGigIdRoute = CheckoutGigIdRouteImport.update({
  id: '/checkout/$gigId',
  path: '/checkout/$gigId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/income': typeof IncomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/proof': typeof ProofRoute
  '/redeem': typeof RedeemRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speak-with-ai': typeof SpeakWithAiRoute
  '/sprint': typeof SprintRoute
  '/upskill': typeof UpskillRoute
  '/checkout/$gigId': typeof CheckoutGigIdRoute
  '/nda/$exchangeId': typeof NdaExchangeIdRoute
  '/r/$username': typeof RUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/income': typeof IncomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/proof': typeof ProofRoute
  '/redeem': typeof RedeemRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speak-with-ai': typeof SpeakWithAiRoute
  '/sprint': typeof SprintRoute
  '/upskill': typeof UpskillRoute
  '/checkout/$gigId': typeof CheckoutGigIdRoute
  '/nda/$exchangeId': typeof NdaExchangeIdRoute
  '/r/$username': typeof RUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/income': typeof IncomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/proof': typeof ProofRoute
  '/redeem': typeof RedeemRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speak-with-ai': typeof SpeakWithAiRoute
  '/sprint': typeof SprintRoute
  '/upskill': typeof UpskillRoute
  '/checkout/$gigId': typeof CheckoutGigIdRoute
  '/nda/$exchangeId': typeof NdaExchangeIdRoute
  '/r/$username': typeof RUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/auth'
    | '/chats'
    | '/dashboard'
    | '/explore'
    | '/income'
    | '/leaderboard'
    | '/marketplace'
    | '/opportunities'
    | '/profile'
    | '/proof'
    | '/redeem'
    | '/sitemap.xml'
    | '/speak-with-ai'
    | '/sprint'
    | '/upskill'
    | '/checkout/$gigId'
    | '/nda/$exchangeId'
    | '/r/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/auth'
    | '/chats'
    | '/dashboard'
    | '/explore'
    | '/income'
    | '/leaderboard'
    | '/marketplace'
    | '/opportunities'
    | '/profile'
    | '/proof'
    | '/redeem'
    | '/sitemap.xml'
    | '/speak-with-ai'
    | '/sprint'
    | '/upskill'
    | '/checkout/$gigId'
    | '/nda/$exchangeId'
    | '/r/$username'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/auth'
    | '/chats'
    | '/dashboard'
    | '/explore'
    | '/income'
    | '/leaderboard'
    | '/marketplace'
    | '/opportunities'
    | '/profile'
    | '/proof'
    | '/redeem'
    | '/sitemap.xml'
    | '/speak-with-ai'
    | '/sprint'
    | '/upskill'
    | '/checkout/$gigId'
    | '/nda/$exchangeId'
    | '/r/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  AuthRoute: typeof AuthRoute
  ChatsRoute: typeof ChatsRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  IncomeRoute: typeof IncomeRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  ProfileRoute: typeof ProfileRoute
  ProofRoute: typeof ProofRoute
  RedeemRoute: typeof RedeemRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeakWithAiRoute: typeof SpeakWithAiRoute
  SprintRoute: typeof SprintRoute
  UpskillRoute: typeof UpskillRoute
  CheckoutGigIdRoute: typeof CheckoutGigIdRoute
  NdaExchangeIdRoute: typeof NdaExchangeIdRoute
  RUsernameRoute: typeof RUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upskill': {
      id: '/upskill'
      path: '/upskill'
      fullPath: '/upskill'
      preLoaderRoute: typeof UpskillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprint': {
      id: '/sprint'
      path: '/sprint'
      fullPath: '/sprint'
      preLoaderRoute: typeof SprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speak-with-ai': {
      id: '/speak-with-ai'
      path: '/speak-with-ai'
      fullPath: '/speak-with-ai'
      preLoaderRoute: typeof SpeakWithAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$username': {
      id: '/r/$username'
      path: '/r/$username'
      fullPath: '/r/$username'
      preLoaderRoute: typeof RUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nda/$exchangeId': {
      id: '/nda/$exchangeId'
      path: '/nda/$exchangeId'
      fullPath: '/nda/$exchangeId'
      preLoaderRoute: typeof NdaExchangeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$gigId': {
      id: '/checkout/$gigId'
      path: '/checkout/$gigId'
      fullPath: '/checkout/$gigId'
      preLoaderRoute: typeof CheckoutGigIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  AuthRoute: AuthRoute,
  ChatsRoute: ChatsRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  IncomeRoute: IncomeRoute,
  LeaderboardRoute: LeaderboardRoute,
  MarketplaceRoute: MarketplaceRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  ProfileRoute: ProfileRoute,
  ProofRoute: ProofRoute,
  RedeemRoute: RedeemRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeakWithAiRoute: SpeakWithAiRoute,
  SprintRoute: SprintRoute,
  UpskillRoute: UpskillRoute,
  CheckoutGigIdRoute: CheckoutGigIdRoute,
  NdaExchangeIdRoute: NdaExchangeIdRoute,
  RUsernameRoute: RUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
